<a href="https://colab.research.google.com/github/vishdas-ai/Pytorch-Deep-Learning/blob/main/pytorch_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

Tue Jan 16 17:20:00 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   63C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## Importing the Torch Library and checking it's version

In [1]:
import torch
print(torch.__version__)

2.1.0+cu121


## Importing Necessary Libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Introduction to Tensors

### Creating a Tensor

### Scalar

In [4]:
scalar=torch.tensor(5)
scalar

tensor(5)

In [5]:
scalar.ndim

0

In [9]:
scalar.shape

torch.Size([])

In [6]:
#get scalar back as an python int
scalar.item()

5

### Vector

In [8]:
vector=torch.tensor([5,5])
vector

tensor([5, 5])

In [10]:
# Dimensions is number of square brackets
vector.ndim

1

In [12]:
#Shape is no of elements
vector.shape

torch.Size([2])

## MATRIX

In [32]:
MATRIX=torch.tensor([[5,5,5],[5,5,5]])
MATRIX

tensor([[5, 5, 5],
        [5, 5, 5]])

In [33]:
MATRIX.ndim

2

In [34]:
MATRIX.shape

torch.Size([2, 3])

## TENSOR

In [44]:
TENSOR=torch.tensor([[[5,5,5],[5,5,5],[5,5,5]],
                      [[5,5,5],[5,5,5],[5,5,5]]])
TENSOR

tensor([[[5, 5, 5],
         [5, 5, 5],
         [5, 5, 5]],

        [[5, 5, 5],
         [5, 5, 5],
         [5, 5, 5]]])

In [45]:
# Tensor is a n dimensional array
TENSOR.ndim

3

In [46]:
TENSOR.shape

torch.Size([2, 3, 3])

### Random Tensors

Why random tensors?

Random numbers are important because the way many neural network learn is that they start with tensors full of of random numbers and then adjust those random numbers to better represent the data

`Start witrh random numbers -> look at the data -> updaterandom numbers -> look at the data -> update random numbers`

In [55]:
# create a random tensor of size (3,4)

random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.4455, 0.5321, 0.4011, 0.4439],
        [0.9146, 0.4958, 0.9678, 0.8402],
        [0.0012, 0.9425, 0.7274, 0.6453]])

In [56]:
random_tensor.ndim

2

In [57]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)


### Zeros and ones


*   Sometimes you'll just want to fill tensors with zeros or ones.


*   This happens a lot with masking (like masking some of the values in one tensor with zeros to let a model know not to learn them)








In [58]:
zeros=torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [59]:
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


## Creating a range and tensors


*  Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

- You can use torch.arange(start, end, step) to do so.

- Where:

    - start = start of range (e.g. 0)
    - end = end of range (e.g. 10)
    - step = how many steps in between each value (e.g. 1)




In [64]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- Sometimes you might want one tensor of a certain type with the same shape as another tensor.

- For example, a tensor of all zeros with the same shape as a previous tensor.

  - To do so you can use **torch.zeros_like(input)** or **torch.ones_like(input)** which return a tensor filled with zeros or ones in the same shape as the input respectively.

In [65]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])