<a href="https://colab.research.google.com/github/vishdas-ai/Pytorch-Deep-Learning/blob/main/pytorch_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

Tue Jan 16 17:20:00 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   63C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## Importing the Torch Library and checking it's version

In [5]:
import torch
print(torch.__version__)

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),


2.1.2


## Importing Necessary Libraries

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Introduction to Tensors

### Creating a Tensor

### Scalar

In [4]:
scalar=torch.tensor(5)
scalar

tensor(5)

In [5]:
scalar.ndim

0

In [9]:
scalar.shape

torch.Size([])

In [6]:
#get scalar back as an python int
scalar.item()

5

### Vector

In [8]:
vector=torch.tensor([5,5])
vector

tensor([5, 5])

In [10]:
# Dimensions is number of square brackets
vector.ndim

1

In [12]:
#Shape is no of elements
vector.shape

torch.Size([2])

## MATRIX

In [32]:
MATRIX=torch.tensor([[5,5,5],[5,5,5]])
MATRIX

tensor([[5, 5, 5],
        [5, 5, 5]])

In [33]:
MATRIX.ndim

2

In [34]:
MATRIX.shape

torch.Size([2, 3])

## TENSOR

In [44]:
TENSOR=torch.tensor([[[5,5,5],[5,5,5],[5,5,5]],
                      [[5,5,5],[5,5,5],[5,5,5]]])
TENSOR

tensor([[[5, 5, 5],
         [5, 5, 5],
         [5, 5, 5]],

        [[5, 5, 5],
         [5, 5, 5],
         [5, 5, 5]]])

In [45]:
# Tensor is a n dimensional array
TENSOR.ndim

3

In [46]:
TENSOR.shape

torch.Size([2, 3, 3])

### Random Tensors

Why random tensors?

Random numbers are important because the way many neural network learn is that they start with tensors full of of random numbers and then adjust those random numbers to better represent the data

`Start witrh random numbers -> look at the data -> updaterandom numbers -> look at the data -> update random numbers`

In [55]:
# create a random tensor of size (3,4)

random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.4455, 0.5321, 0.4011, 0.4439],
        [0.9146, 0.4958, 0.9678, 0.8402],
        [0.0012, 0.9425, 0.7274, 0.6453]])

In [56]:
random_tensor.ndim

2

In [57]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)


### Zeros and ones


*   Sometimes you'll just want to fill tensors with zeros or ones.


*   This happens a lot with masking (like masking some of the values in one tensor with zeros to let a model know not to learn them)








In [58]:
zeros=torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [59]:
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


## Creating a range and tensors


*  Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

- You can use torch.arange(start, end, step) to do so.

- Where:

    - start = start of range (e.g. 0)
    - end = end of range (e.g. 10)
    - step = how many steps in between each value (e.g. 1)




In [64]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- Sometimes you might want one tensor of a certain type with the same shape as another tensor.

- For example, a tensor of all zeros with the same shape as a previous tensor.

  - To do so you can use **torch.zeros_like(input)** or **torch.ones_like(input)** which return a tensor filled with zeros or ones in the same shape as the input respectively.

In [65]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

- There are many different tensor datatypes available in PyTorch.

- Some are specific for CPU and some are better for GPU.

- Getting to know which is which can take some time.

- Generally if you see torch.cuda anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

- The most common type (and generally the default) is torch.float32 or torch.float.

- This is referred to as "32-bit floating point".

- But there's also 16-bit floating point (torch.float16 or torch.half) and 64-bit floating point (torch.float64 or torch.double

In [14]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([4]), torch.float32, device(type='cpu'))


## Getting information from tensors
- Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

- We've seen these before but three of the most common attributes you'll want to find out about tensors are:

    - shape - what shape is the tensor? (some operations require specific shape rules)
    - dtype - what datatype are the elements within the tensor stored in?
    - device - what device is the tensor stored on? (usually GPU or CPU)

In [16]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.7748, 0.0016, 0.4704, 0.2347],
        [0.2641, 0.3071, 0.3177, 0.0346],
        [0.4303, 0.0553, 0.4228, 0.9515]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Matrix multiplication 

- One of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.

- PyTorch implements matrix multiplication functionality in the torch.matmul() method.

In [17]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

#### Element-wise multiplication
`[1*1, 2*2, 3*3] = [1, 4, 9]`

In [18]:
tensor * tensor

tensor([1, 4, 9])

#### Matrix multiplication
`[1*1 + 2*2 + 3*3] = [14]`

In [19]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [20]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)


- You can do matrix multiplication by hand but it's not recommended.

- The in-built torch.matmul() method is faster

In [25]:
tensor

tensor([1, 2, 3])

In [26]:
len(tensor)

3

In [28]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 649 µs, sys: 840 µs, total: 1.49 ms
Wall time: 930 µs


tensor(14)

In [29]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 229 µs, sys: 75 µs, total: 304 µs
Wall time: 264 µs


tensor(14)

### One of the most common errors in deep learning (shape errors)

Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.

In [30]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

- We can make matrix multiplication work between tensor_A and tensor_B by making their inner dimensions match

- **In the context of matrix multiplication, the inner dimension refers to the number of columns in the first matrix or the number of rows in the second matrix**

- One of the ways to do this is with a transpose (switch the dimensions of a given tensor).

- You can perform transposes in PyTorch using either:

  - torch.transpose(input, dim0, dim1) - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.

   - tensor.T - where tensor is the desired tensor to transpose.


In [32]:
print(tensor_A) #3*2
print(tensor_B) #3*2

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [33]:
# Perform transose of the matrix B using "T"
# Now the inner dimesnions are matching


print(tensor_A)                #3*2
print(tensor_B.T) # tensor.T   #2*3

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [35]:
# Now lets tensor_A with the transpose of tensor_B
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B.T) # (this will error)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [36]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])
